# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36ac7717c1a89e2d4cdcf7389bc77ae2388692ddccae48fa82c592dc4db9adc89035ebbfa82de5a68538b305bee7a9d1440de5a048091b8c5f571cc089d33526

test:
  secret_key_base: 87c819ca9fd76d7c8b68676d8e29219f04e08943d5f12a40caa6421a896744da279b986eb6f2a7ec3e3032326bd67b5d1d811270d99caab479ac532f2a1939d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
